cache:
  bundler: true
  directories:
    - Carthage/Builds

install:
    # Installing all gems from bundler
    - bundle install
matrix: 
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.1
      script: 
        - bundle exec fastlane test
        - bundle exec danger || true
        - bundle exec fastlane lint_current_podspec
    